### ISSUE TITLE
Build Error: no member named 'view' in 'std::stringstream'

### ISSUE THREAD

**Issue by Tanikai** [LukasPietzschmann/uulm-mensa-tui#1]
### Issue

I get the following error when trying to build the TUI:

```
/Users/kai/Projects/uulm-mensa-tui/src/main.cpp:68:48: error: no member named 'view' in 'std::stringstream'
        const json& api_response = json::parse(result.view());
                                               ~~~~~~ ^
```

### Expected behavior

Should build without errors.

### Additional Information

- OS: macOS Sonoma 14.0
- cmake version: 3.27.7

**Comment by LukasPietzschmann** [comment]
Yeah, Apple ships a custom build of clang which doesn't have full support for C++ 20. Try building with a recent version of g++ (I use 13.2).

You can instruct CMake to use g++ by setting the `CMAKE_CXX_COMPILER` variable.

**Comment by LukasPietzschmann** [comment]
Could you resolve your issue in the meantime?

**Comment by Tanikai** [comment]
No; I have no experience in CMake, so I'll have to look it up sometime in the next days.

**Comment by LukasPietzschmann** [comment]
Closed due to inactivity. But feel free to reopen this issue at any time!
